terraform {
  required_providers {
    openstack = {
      source  = "terraform-provider-openstack/openstack"
      version = "~> 2.0"
    }
    t4o = {
      source  = "registry.terraform.io/trilio-demo/t4o"
      version = "0.1.0"
    }
  }
}

provider "openstack" {}
provider "t4o" {}

# ====================================================================
# 1. THE ORIGINAL INFRASTRUCTURE
# ====================================================================
# This is the VM you created initially. If this VM is deleted, Terraform
# will try to recreate it. We will use the import block below to rescue
# this state when Trilio restores it!
resource "openstack_compute_instance_v2" "example_vm" {
  name        = "restored-example-vm"
  flavor_name = "m1.small"
  image_name  = "cirros"
}

# The workload that protects the VM
resource "t4o_workload" "example_workload" {
  name             = "example-workload"
  description      = "Workload protecting the example VM"
  workload_type_id = data.t4o_workload_types.all.workload_types[0].id
  
  instance_ids = [
    openstack_compute_instance_v2.example_vm.id
  ]
}

data "t4o_workload_types" "all" {}

# ====================================================================
# 2. DISASTER RECOVERY (RESTORE OPERATION)
# ====================================================================
# During a disaster recovery scenario, uncomment the resource below.
# Provide the snapshot_id from Trilio that you wish to restore.

/*
resource "t4o_restore" "dr_restore" {
  name        = "dr-failover-restore"
  description = "One-click restore triggered via Terraform"
  snapshot_id = "INSERT-SNAPSHOT-UUID-HERE"
  type        = "oneclick"
}
*/

# ====================================================================
# 3. DYNAMIC STATE ADOPTION
# ====================================================================
# The import block runs during the PLAN phase.
# To adopt the VM dynamically, we must query the results of the restore.

/*
data "t4o_restore_details" "latest" {
  # This targets the restore we just executed above
  restore_id = t4o_restore.dr_restore.id
}

import {
  to = openstack_compute_instance_v2.example_vm
  
  # This magically intercepts Terraform's attempt to create a new VM, 
  # reads the new UUID generated by Trilio out of the data source, 
  # and adopts it into the example_vm resource!
  id = data.t4o_restore_details.latest.restored_instances["restored-example-vm"].id
}
*/
